<!DOCTYPE html>
<html>
<head>
    <?php echo Yaf_View_Simple::render('common/head.phtml'); ?>
</head>
<body>
<div class="ui container">
    <?php echo Yaf_View_Simple::render('common/nav.phtml'); ?>

    <div class="ui stackable grid">
        <main class="eleven wide column">
            <?php foreach ($articleList as $k => $v): ?>
                <article>
                    <h1><a href="/article/daile?id=<?php echo $v['id']; ?>"><?php echo $v['title']; ?></a></h1>
                    <p><?php echo date('Y-m-d H:i:s', $v['ctime']); ?></p>
                    <!--<p><img class="ui small left floated image" src="/img/image.png"></p>
                    <p><a href="#">Read more</a> <i class="ui icon arrow right"></i></p>-->
                </article>
                <div class="ui divider"></div>
            <?php endforeach; ?>

            <!-- Pagination -->
            <!--<div class="ui pagination menu"></div>-->
        </main>

        <?php echo Yaf_View_Simple::render('common/right.phtml'); ?>

    </div>
</div>

<?php echo Yaf_View_Simple::render('common/footer.phtml'); ?>

</body>
</html>

